[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="basePackage" type="java.lang.String" --]
[#-- @ftlvariable name="links" type="java.util.Map<String, org.example.Link>" --]
[#-- @ftlvariable name="attributes" type="java.util.Map<String, String>" --]
[#-- @ftlvariable name="queryAttributes" type="java.util.Map<String, String>" --]
[#-- @ftlvariable name="hasQuery" type="boolean" --]
[#-- @ftlvariable name="name" type="String" --]
