[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="query" type="org.example.Query" --]
[#-- @ftlvariable name="resource" type="org.example.Resource" --]
[#-- @ftlvariable name="secondaryPathElement" type="java.lang.String" --]
[#-- @ftlvariable name="primaryPathElement" type="java.lang.String" --]
[#-- @ftlvariable name="pathElement" type="java.lang.String" --]
[#-- @ftlvariable name="useEtags" type="boolean" --]
[#-- @ftlvariable name="states" type="java.util.List<org.example.State>" --]
[#-- @ftlvariable name="cacheControl" type="javax.ws.rs.core.CacheControl" --]
[#-- @ftlvariable name="queries" type="java.util.List<org.example.Query>" --]
[#-- @ftlvariable name="usesInMemory" type="boolean" --]
[#-- @ftlvariable name="resources" type="java.util.List<org.example.Resource>" --]
[#-- @ftlvariable name="secondaryAttributes" type="java.util.Map<String, String>" --]
[#-- @ftlvariable name="secondaryName" type="java.lang.String" --]
[#-- @ftlvariable name="primaryName" type="String" --]
[#-- @ftlvariable name="basePackage" type="java.lang.String" --]
[#-- @ftlvariable name="links" type="java.util.Map<String, org.example.Link>" --]
[#-- @ftlvariable name="attributes" type="java.util.Map<String, String>" --]
[#-- @ftlvariable name="hasQuery" type="boolean" --]
[#-- @ftlvariable name="name" type="String" --]
